### ISSUE TITLE
mutual-ra example fails: 

### ISSUE THREAD

**Issue by brenzi** [apache/teaclave-sgx-sdk#72]
I could build the mutual-ra example, but running it fails: 

(I've successfully tried remoteattestation before)

```
> ./app --server
[+] Home dir is /home/brenzi
[-] Open token file /home/brenzi/enclave.token error! Will create one.
[+] Init Enclave Successful 2!
Running as server...
new client from V4(127.0.0.1:55116)
Entering ocall_sgx_init_quote
eg = [215, 10, 0, 0]
get_sigrl_from_intel fd = 7
GET /attestation/sgx/v3/sigrl/00000ad7 HTTP/1.1
HOST: /attestation/sgx/v3/sigrl/


write complete
read_to_end complete
HTTP/1.1 200 OK
content-length: 0
request-id: f2af59a8e5a74c0888f85976868f356b
date: Sat, 09 Feb 2019 15:11:49 GMT
Connection: keep-alive


parse_response_sigrl
parse result Ok(Complete(145))
parse responseResponse { version: Some(1), code: Some(200), reason: Some("OK"), headers: [Header { name: "content-length", value: [48] }, Header { name: "request-id", value: [102, 50, 97, 102, 53, 57, 97, 56, 101, 53, 97, 55, 52, 99, 48, 56, 56, 56, 102, 56, 53, 57, 55, 54, 56, 54, 56, 102, 51, 53, 54, 98] }, Header { name: "date", value: [83, 97, 116, 44, 32, 48, 57, 32, 70, 101, 98, 32, 50, 48, 49, 57, 32, 49, 53, 58, 49, 49, 58, 52, 57, 32, 71, 77, 84] }, Header { name: "Connection", value: [107, 101, 101, 112, 45, 97, 108, 105, 118, 101] }] }
OK Operation Successful
content length = 0
Report creation => success [131, 215, 25, 231, 125, 234, 202, 20, 112, 246, 186, 246, 42, 77, 119, 67, 3, 200, 153, 219, 105, 2, 15, 156, 112, 238, 29, 252, 8, 199, 206, 158]
rand finished
Entering ocall_get_quote
quote size = 1116
sgx_calc_quote_size returned SGX_SUCCESS.
rsgx_verify_report passed!
qe_report check passed
rhs hash = FFEDA96713875ED924BA67F64F1B49B236B35B7F45C886AE0208D3CC612BC519
report hs= FFEDA96713875ED924BA67F64F1B49B236B35B7F45C886AE0208D3CC612BC519
get_report_from_intel fd = 7
POST /attestation/sgx/v3/report HTTP/1.1
HOST: test-as.sgx.trustedservices.intel.com
Content-Length:1512
Content-Type: application/json

{"isvEnclaveQuote":"AgABANcKAAAFAAQAAAAAAAru8I2/DnejWZb384uulZkAAAAAAAAAAAAAAAAAAAAACAj//wGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAAAAD7avk9sxG7Cb5wZfdofUuZ9vfSc7ABIZIggr+2vrSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACD1xnnferKFHD2uvYqTXdDA8iZ22kCD5xw7h38CMfOngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAluyqsTJVW/JfukTFDKokm1GEiTXqWXcgwqLHpC6sWSFVy/aj5/hFAqDwOMbd5EqMLrxKJft+8VOskB/u4svZ1qAIAAE1GTdP/w2OhqwuYVN0s5mSyMGoJGPdnxu08JiY+B6EtV7HnnqCKFhpLLZXJ8u3KfHrRDmFzC4sLPHgzmXBvbOl2OWA1jrTSfpoA5ZyWSFIA0HJXdSB7emgB8fU87q3hlkX18XFssldM3OcLzx7nigvxau5zil+z/zWZNct3cttZlnC1mRi4fcD7POAy8hLzLyZiIpRUSttMunCqeGLhTvBRkJ3xzXT+0VL4ykgnImXaRglU1ktOcatX7Auq3y0I9dH3vaG5J5Ws2kpNXzpx/jG+omwJgYwyMV7i6wa7X2NZQQfbmph7NWgXQ4qBe5LW35mH5H5JfS6zCibfyz6KqGh6ENt/3dSe7N6dftHDf/tS9NYC0+FFQT77OEzLH3Rmss/1b5FJkeS0l/Z85mgBAAC0WTyDVw2ldflcN47IQLEVI0RVNLz6Oh25n3oNbbV5IiyiyHlnL/VIiUgn4kTwGHLXmcDa38fkX58W9Gw2WCQIQIX7klm8TIGB3mQ0uwLeLl+DQlCjcWfb8KRIjhnfXgpJ3ywrFh/XryHm/BOmk6BSZMybmhUuRGHN9vCLnj0BY50wcvBrl1yy+U7MMK8bGkfyr4HK3Ggp7hDycgqgxKHwyPKTucaQyxZ8cvx5rtc8WKs7ggN+zo0MZb7GEFHAyvvNhcc4C6ON0s2qg5H7fXFqcGpwGiL2TGzGCQKXyMFJE7CTZ8dpJGBTATEU7Qx22/k32etVCmIq68Coh9KVcaCzRtJwx5tevlAD+Wmt+pUmP4uBvoWLEpQYrgqAZ0hzpRGI5vQeFRjDteeL4Xk4wbY9V7RyiySVrCMFLXFcV0FSf37Gd+RB8wGldPi20a4PxLQSGWFVkUiFDAJSeq/0tyi3NTPIajtNPH7yx1JzLQb4bExXvhv9MyU4"}

write complete
read_to_end complete
resp_string = HTTP/1.1 400 Bad Request
content-length: 0
request-id: e602f0cbac9a4acca68ad3acdc2ae687
date: Sat, 09 Feb 2019 15:11:55 GMT
Connection: keep-alive


parse_response_attn_report
parse result Ok(Complete(154))
DBG:400
Unknown error occured
content length = 0
thread panicked at 'Box<Any>', /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libcore/slice/mod.rs:2535:10
stack backtrace:
   0: sgx_tstd::sys::backtrace::tracing::gcc_s::unwind_backtrace
   1: sgx_tstd::sys_common::backtrace::print
   2: sgx_tstd::panicking::default_panic_handler
   3: sgx_tstd::panicking::rust_panic_with_hook
   4: sgx_tstd::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   7: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   8: mra::create_attestation_report
   9: run_server
  10: sgx_run_server
  11: enter_enclave
  12: <unknown>
  13: <unknown>
Illegal instruction (core dumped)
```
client:
```
./app --client
[+] Home dir is /home/brenzi
[-] Open token file /home/brenzi/enclave.token error! Will create one.
[+] Init Enclave Successful 2!
Running as client...
Entering ocall_sgx_init_quote
eg = [215, 10, 0, 0]
get_sigrl_from_intel fd = 6
GET /attestation/sgx/v3/sigrl/00000ad7 HTTP/1.1
HOST: /attestation/sgx/v3/sigrl/


write complete
read_to_end complete
HTTP/1.1 200 OK
content-length: 0
request-id: e7ef7b17d51e4fd4ac4a5ce5f9f42c6a
date: Sat, 09 Feb 2019 15:11:49 GMT
Connection: keep-alive


parse_response_sigrl
parse result Ok(Complete(145))
parse responseResponse { version: Some(1), code: Some(200), reason: Some("OK"), headers: [Header { name: "content-length", value: [48] }, Header { name: "request-id", value: [101, 55, 101, 102, 55, 98, 49, 55, 100, 53, 49, 101, 52, 102, 100, 52, 97, 99, 52, 97, 53, 99, 101, 53, 102, 57, 102, 52, 50, 99, 54, 97] }, Header { name: "date", value: [83, 97, 116, 44, 32, 48, 57, 32, 70, 101, 98, 32, 50, 48, 49, 57, 32, 49, 53, 58, 49, 49, 58, 52, 57, 32, 71, 77, 84] }, Header { name: "Connection", value: [107, 101, 101, 112, 45, 97, 108, 105, 118, 101] }] }
OK Operation Successful
content length = 0
Report creation => success [131, 215, 25, 231, 125, 234, 202, 20, 112, 246, 186, 246, 42, 77, 119, 67, 3, 200, 153, 219, 105, 2, 15, 156, 112, 238, 29, 252, 8, 199, 206, 158]
rand finished
Entering ocall_get_quote
quote size = 1116
sgx_calc_quote_size returned SGX_SUCCESS.
rsgx_verify_report passed!
qe_report check passed
rhs hash = 90C5CE63E4F2A0D9A52AA70E190B1834CA0BCBF9DBA99BD6CBBE94347DA5C149
report hs= 90C5CE63E4F2A0D9A52AA70E190B1834CA0BCBF9DBA99BD6CBBE94347DA5C149
get_report_from_intel fd = 6
POST /attestation/sgx/v3/report HTTP/1.1
HOST: test-as.sgx.trustedservices.intel.com
Content-Length:1512
Content-Type: application/json

{"isvEnclaveQuote":"AgABANcKAAAFAAQAAAAAAAru8I2/DnejWZb384uulZkAAAAAAAAAAAAAAAAAAAAACAj//wGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAHAAAAAAAAAAAD7avk9sxG7Cb5wZfdofUuZ9vfSc7ABIZIggr+2vrSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACD1xnnferKFHD2uvYqTXdDA8iZ22kCD5xw7h38CMfOngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD3VkQE9HMzRLpYl739vjJAXW7M0+LkVkpZEYSNxuhP3uhIEzSSptjap1qrmRJ58qWdVsOQgbhs/yEVDho4E2wcqAIAAKVBI56wqUNf3QF/c2+KUOP54xwy4ghBptLW7tWwEAPU7UpOWTZ11vmCAl40FZXgM2w5iVUKNuielWnpEb90zf8pw39Hi0j3coRVv7xp9hDjBGFRTkNKu98P8Q4oN2VHWPN/gPkLgFctCbc3kUK0/YImPI1mGQoby6t/MYfR6WclHRsJHe3seU+uMI12mfAskRoxNsyHIK16K8XwSxo7f9xtM5+jYMNs4wVBnZyK6aGXnxWjis6o6YOrF7+FHgsS28q8jfi8lymY5wqKQZGZZIcNb55gDdllMg8KXcOa/L6RooN850sy8/abV3B6bOXq5QG+WOGR+IY07/gJ8fg9hrm6V89ph3sRqYsRn8cWrxYfBR9WJK6YjWqxk1TeRj1guL51t2xSKjmHGU1J5mgBAAAYDcQp/eL3p6K4JmHKAiBfl5bvOZ47tevn1ryLlTB5nyRaAmaK9Cfo6K63Dl1/qgWmU6PfONen3ON8syN1XXz+lNLcK0CjMfjcHCs81telfqb6f9sRrfXqY8yA4sNGlpQBiYZXNzlfKPv4MmZMd/yahfRTqssDHGj+AXNhZEfFvAo/faDH9rOnZfqZzS1+fMf78Eb8X97Xrk9xhscWfLWhpRrWFPNHDqPbHR+851J4Tcilw8L5xrBWh2egX+uzPjtrv4QFCwm/56WnAoMWpJ9m0BdRA+hiUs2fcfviROYraz6h9qxvz9oeLaqjrFwPW/SjVkFAqVBpMgndpLmeoE/1f+UbpC8FPg7C6eKUVw0bMGv9O2f30h9YSuFXo2gIOZnECXdWAJ4lmApT7PyGpdPtuu2qXoVy48/r59/H7Oy/cL0/cm62t5qjHe/JbS5PGp+MZlQ2Lk3hiCxVZvyd1BrMTAfkF9vGxYdR+b4HvVZYfYfOETl5b97E"}

write complete
read_to_end complete
resp_string = HTTP/1.1 400 Bad Request
content-length: 0
request-id: d54572d01d8f4460b59ca32b9c7bd114
date: Sat, 09 Feb 2019 15:11:55 GMT
Connection: keep-alive


parse_response_attn_report
parse result Ok(Complete(154))
DBG:400
Unknown error occured
content length = 0
thread panicked at 'Box<Any>', /rustc/da6ab956e1002517803ecd38b904504a1223274b/src/libcore/slice/mod.rs:2535:10
stack backtrace:
   0: sgx_tstd::sys::backtrace::tracing::gcc_s::unwind_backtrace
   1: sgx_tstd::sys_common::backtrace::print
   2: sgx_tstd::panicking::default_panic_handler
   3: sgx_tstd::panicking::rust_panic_with_hook
   4: sgx_tstd::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   7: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
   8: mra::create_attestation_report
   9: run_client
  10: sgx_run_client
  11: enter_enclave
  12: <unknown>
  13: <unknown>
Illegal instruction (core dumped)
```

**Comment by dingelish** [comment]
Hmmm this is the same error as the last one:
```
resp_string = HTTP/1.1 400 Bad Request
```
Correct it here
https://github.com/baidu/rust-sgx-sdk/blob/dd6e4a2c98b2011a13812bf9e7e7d9a8614928c5/samplecode/mutual-ra/enclave/src/lib.rs#L402

**Comment by brenzi** [comment]
of course, I should've seen that....

changed to `SGX_UNLINKABLE_SIGNATURE` and it worked
